[package]
name = "game_client"
version = "0.1.0"
edition = "2021"

[dependencies]
net-utils = { path = "../net-utils" }
anyhow = "1.0"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.27", features = ["full"] }
