[package]
name = "_0x64"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = {version = "3.2.22", features = ["derive"]}
#aead = "0.5.1" todo
#ansi_term = "0.12.1"
chrono = "0.4"
rand = "0.8.5"
